### ISSUE TITLE
New version release with 100% Hungarian translation

### ISSUE THREAD

**Issue by ovari** [OpenChemistry/avogadroapp#207]
If not done, could you please merge the Hungarian translations as they should be at 100%?

Could you please release a new stable version with the Hungarian translations to enable testing?

Thank you

**Comment by ghutchis** [comment]
Yes, the translations are merged fairly regularly, and picked up with automated updates.

Since many of the `avogadrolibs` strings come through in the UI, that's certainly the next step. We will probably be releasing a 1.96 in late September / early October and I'll absolutely note your work - you've also given some great suggestions / comments on Weblate.

There may be a 1.95.2 release to resolve #206 - in principal you should be able to download the `i18n` plugin (from the autogenerated [`avogadro-i18n`](https://github.com/openchemistry/avogadro-i18n/) repo but that's not working properly yet.

**Comment by ovari** [comment]
Will the Hungarian translations be available by installing the Avogadroapp or does more need to be done?

We would prefer that the Hungarian translations are available in the default installation without the need to install extensions/add-on/plug-ins.

Thank you

**Comment by ghutchis** [comment]
> Will the Hungarian translations be available by installing the Avogadroapp or does more need to be done?

The new translations will be available with all future releases.

I mentioned that users will be able to install updated translations through a download update - it's just not working in this current release. But translations are part of all releases - that's the point of the `merge` - as you update from Weblate, they will show up in our code - distributed as part of the source, etc.

**Comment by ovari** [comment]
https://hosted.weblate.org/projects/avogadro/avogadrolibs/ for Hungarian is done as it is at 100%.

@ghutchis :
1. Can you please provide answers to the comments in Weblate?
2. Can you please advise where MoleQueue translations are hosted?
3. Can an Avogadro2 release please be created, say version 1.95.2, with the Hungarian translations included and available on [Flathub](https://flathub.org/apps/details/org.openchemistry.Avogadro2)?

Thank you

**Comment by ghutchis** [comment]
Thanks for the translation work. I will work to respond to your comments on Weblate over the next few days. Avogadro is a volunteer project and I can only devote a few hours to it. Your suggestions are most welcome, but hunting down the strings takes time.

I don't handle Molequeue - but I did respond to your question. That project would need to set up its own translations.

At the moment, as referenced in #206 there seem to be issues picking up the translations, so it would be pointless to make a new release until that bug is resolved.

I really appreciate all the translation work and suggestions - there are a *lot* of strings. But I'm splitting my time between features, bug fixes, etc. in addition to research and teaching.

In the meantime, the AppImage is built by GitHub action, so that will have fixes as they occur:
https://nightly.link/OpenChemistry/avogadrolibs/workflows/build_cmake/master/Avogadro2.AppImage

**Comment by ovari** [comment]
Thank you for your comment.

> In the meantime, the AppImage is built by GitHub action, so that will have fixes as they occur:
https://nightly.link/OpenChemistry/avogadrolibs/workflows/build_cmake/master/Avogadro2.AppImage

For some reason can't open Avogadro2 using the nightly AppImage with Linux Mint 20.2 Cinnamon.

Thank you once again.

**Comment by ghutchis** [comment]
Aha.. I think I found the problem!

<img width="285" alt="Screen Shot 2022-06-14 at 8 36 45 PM" src="https://user-images.githubusercontent.com/41128/173712059-529a2aef-acbc-49ce-8227-62ae30531737.png">

After successfully loading translations, it continued in a loop .. which would then unload the translations. 🙄 

Do AppImages work for you now?

**Comment by ghutchis** [comment]
(The Spanish translation is not 100% .. but finally shows up!)

**Comment by ovari** [comment]
> Aha.. I think I found the problem!

Congratulations!

> Do AppImages work for you now?

Can you please advise the link to where the AppImages are?

Thank you

**Comment by ghutchis** [comment]
Give this a try:
https://github.com/OpenChemistry/avogadrolibs/suites/6945362230/artifacts/270822145

I'm sure there are probably some bare strings. I'll be reaching out to translation contributors over the next few weeks now that it should be working.

I'm also thinking carefully about the best way to handle the dialog / menu you're describing. It's a good idea, but it may take a bit to figure out the best implementation in Qt / C++.

**Comment by ovari** [comment]
> I'm also thinking carefully about the best way to handle the dialog / menu you're describing. It's a good idea, but it may take a bit to figure out the best implementation in Qt / C++.

Sorry, don't understand what dialog / menu you are referring to. Can you please provide some more information? Thank you

**Comment by ghutchis** [comment]
Sorry - you had suggested to add a dialog or menu for users to switch translations between "System Setting" and various languages / localizations: https://github.com/OpenChemistry/avogadroapp/issues/206#issuecomment-916569841

**Comment by ghutchis** [comment]
Languages:  ("Afrikaans", "العربية", "Български", "Bosanski", "Català", "Català", "Čeština", "Dansk", "Deutsch", "Ελληνικά", "Australian English", "Canadian English", "British English", "Esperanto", "Español de España", "Eesti", "Euskara", "فارسی", "Suomi", "Français", "Français canadien", "Galego", "עברית", "हिन्दी", "Hrvatski", "Magyar", "Indonesia", "Italiano", "日本語", "Ქართული", "ಕನ್ನಡ", "한국어", "Melayu", "Norsk bokmål", "Nederlands", "", "Polski", "Português", "Português", "Română", "Русский", "संस्कृत भाषा", "Slovenčina", "Slovenščina", "Shqip", "Српски", "Svenska", "தமிழ்", "తెలుగు", "ไทย", "Türkçe", "ئۇيغۇرچە", "Українська", "Tiếng Việt", "简体中文", "繁體中文")

**Comment by ovari** [comment]
> Languages: ("Afrikaans", "العربية", "Български", "Bosanski", "Català", "Català", "Čeština", "Dansk", "Deutsch", "Ελληνικά", "Australian English", "Canadian English", "British English", "Esperanto", "Español de España", "Eesti", "Euskara", "فارسی", "Suomi", "Français", "Français canadien", "Galego", "עברית", "हिन्दी", "Hrvatski", "Magyar", "Indonesia", "Italiano", "日本語", "Ქართული", "ಕನ್ನಡ", "한국어", "Melayu", "Norsk bokmål", "Nederlands", "", "Polski", "Português", "Português", "Română", "Русский", "संस्कृत भाषा", "Slovenčina", "Slovenščina", "Shqip", "Српски", "Svenska", "தமிழ்", "తెలుగు", "ไทย", "Türkçe", "ئۇيغۇرچە", "Українська", "Tiếng Việt", "简体中文", "繁體中文")

The Hungarian language written in Hungarian should start with a lowercase letter, i.e. `magyar`. Thank you

**Comment by ovari** [comment]
Closing as nightly version of Avogadro2 can be shown in Hungarian. Thank you
