### ISSUE TITLE
Build error with qt 5.8.0

### ISSUE THREAD

**Issue by rezso** [OpenChemistry/avogadroapp#54]
If I try to compile avogadro2 app with qt 5.8.0, I get this error:

avogadro/mainwindow.cpp: In function 'bool Avogadro::ToolSort(const Avogadro::QtGui::ToolPlugin*, const Avogadro::QtGui::ToolPlugin*)':
avogadro/mainwindow.cpp:1555:13: error: 'const class Avogadro::QtGui::ToolPlugin' has no member named 'priority'; did you mean 'property'?
   return a->priority() < b->priority();
             ^~~~~~~~
avogadro/mainwindow.cpp:1555:29: error: 'const class Avogadro::QtGui::ToolPlugin' has no member named 'priority'; did you mean 'property'?
   return a->priority() < b->priority();
                             ^~~~~~~~

After reverting https://github.com/OpenChemistry/avogadroapp/commit/e509e7734a40d58b0f0297b5619dc37445eb6fd8 the build is successful.

**Comment by cryos** [comment]
The avogadrolibs project needs compiling, that is a new function, I just checked and the submodule already included those changes, but you may not have updated/rebuilt it.

  git submodule update

in the openchemistry source tree will update it, and then in the build tree

  cmake --build . --target avogadroapp

would trigger a build that should trigger both avogadrolibs and avogadroapp, or you can go into each one but make sure you build the install target so that the updated headers/libs get installed in the build prefix. I am using Qt 5.8.0 on Linux without issues, and just verified things compile here.

**Comment by ghutchis** [comment]
This works for me on Mac too. I'm closing this. If you have trouble building the current versions from git (using Marcus's instructions) please re-open this issue.
